#include <iostream>
using namespace std;
int main ()
{
    cout << "\t\t\t        -----" << endl;
    cout << "\t\t\t       (Start)" << endl;
    cout << "\t\t\t        -----" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << "\t\t\t ---------------------" << endl;
    cout << "\t\t\t/(a*2)^(6+b*2)/(10-b)/" << endl;
    cout << "\t\t\t--------------------" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << "\t\t\t --------------------------" << endl;
    cout << "\t\t\t|myltiply b by 2 in (6+b*2)|" << endl;
    cout << "\t\t\t --------------------------" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << "\t\t  -----------------------------------------" << endl;
    cout << "\t\t |add 6 to the result of multiplying b by 2|" << endl;
    cout << "\t\t  -----------------------------------------" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << "\t\t\t     -------------" << endl;
    cout << "\t\t\t    |calculate a*2|" << endl;
    cout << "\t\t\t     -------------" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << " ------------------------------------------------------";
    cout << "--------------------------------------" << endl;
    cout << "|to raise the calculation result a*2 to the calculation";
    cout << "result in the power of a number(6+b*2)|"  << endl;
    cout << " ------------------------------------------------------";
    cout << "--------------------------------------" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << "\t\t\t     --------------" << endl;
    cout << "\t\t\t    |calculate 10-b|" << endl;
    cout << "\t\t\t     --------------" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << " -------------------------------------------------------------------";
    cout << "-----------------" << endl;
    cout << "|divide the result of the calculation of the first expression by the";
    cout << "second expression|" << endl;
    cout << " -------------------------------------------------------------------";
    cout << "-----------------" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << "\t\t\t ---------------------" << endl;
    cout << "\t\t\t|write down the answer|" << endl;
    cout << "\t\t\t ---------------------" << endl;
    cout << "\t\t\t\t ||" << endl;
    cout << "\t\t\t\t \\/" << endl;
    cout << "\t\t\t\t ---" << endl;
    cout << "\t\t\t\t(end)" << endl;
    cout << "\t\t\t\t ---" << endl;
    return 0;
}
